### ISSUE TITLE
Enable any changes needed for https only 

### ISSUE THREAD

**Issue by kjallen** [UCLALibrary/ucla-prrla#74]
We were looking to run https only on the prrla application and noticed we ran into a few errors or any hardcoded http links in the application. Could the application be updated to work either with http or https?

**Comment by Hlopec** [comment]
Hi, @kjallen!
Please provide wich errors you see.
Thank you!

**Comment by cachemeoutside** [comment]
Hi @Hlopec,

There appears to be issues with the site grabbing solr values when accessing the site via HTTPS. The message Backend error: Problems with API shows up. We're not sure what the issue is, I've configured our test-solr.library.ucla.edu to listen for HTTPS. Maybe it's as simple as changing the solr URL to https?(only do this for test environment for now). Once we verify that HTTPS is working, we'll be forcing all traffic to HTTPS.

Here are two example URLs that act differently:
http://test-prl.library.ucla.edu/explore-collections
https://test-prl.library.ucla.edu/explore-collections

**Comment by Hlopec** [comment]
done, please check it.

**Comment by cachemeoutside** [comment]
Hi @Hlopec,

I pushed the latest changes out. It appears that we're making progress after the solr URL change to https, but there's still a quirk. I'm able to see the collections now, but if I collapse an item in the "Browse by Institution" menu from:

https://test-prl.library.ucla.edu/explore-collections

I'll get the same backend error. The improvement is that It's able to list the institutions and collections now. "Browse by Collections" appears to work fine after this change. I'm not sure what else might be the issue at this point.

--EDIT--
After looking at my browser console log, looks like this might be an issue with multi-valued fields on solr. @kjallen @pghorpade @markmatney take a look at this URL.

https://test-solr.library.ucla.edu/solr/prrla/select?q=institutionName:%22Chinese%20University%20of%20Hong%20Kong%22&rows=-1&facet=true&facet.field=collectionName&facet.sort=count&facet.mincount=1&facet.limit=-1&sort=collectionName%20asc&wt=json&indent=true&json.wrf=__ng_jsonp__.__req101.finished

**Comment by Hlopec** [comment]
please, try now.

**Comment by cachemeoutside** [comment]
Looks like it's resolved. Closing. Thanks @Hlopec! We'll be submitting another similar request for production changes when we're ready to go all HTTPS.
